# Generated by Django 4.1.4 on 2023-03-17 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=900)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_title', models.CharField(max_length=255)),
                ('story_body', models.CharField(max_length=5000000)),
                ('category', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='images/')),
                ('storydate_posted', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
