# Generated by Django 4.1.4 on 2023-03-17 21:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_title', models.CharField(max_length=255)),
                ('story_body', models.CharField(max_length=5000000)),
                ('category', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='images/')),
                ('storydate_posted', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Politics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_title', models.CharField(max_length=255)),
                ('story_body', models.CharField(max_length=5000000)),
                ('category', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='images/')),
                ('storydate_posted', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_title', models.CharField(max_length=255)),
                ('story_body', models.CharField(max_length=5000000)),
                ('category', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='images/')),
                ('storydate_posted', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
